services:
  unifiedachievementplatform:
    image: unifiedachievementplatform
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
